### ISSUE TITLE
Optimize jobs segment

### ISSUE THREAD

**Issue by mcmd1962** [banga/powerline-shell#117]
The current code of jobs.py is invoking 2 times a subprocess to determine the number of background jobs in the current shell. On my (slow) system, this segment is one of the slowest there is.
The subprocesses could be avoided by using the information in the /proc/*/stat files instead. Something like the following:

```
myppid = os.getppid()
CountJobs = {}
ProcessPid = -1

for f in os.listdir('/proc'):
    pathname = os.path.join('/proc', f)
    fstat = os.stat(pathname)

    if fstat.st_uid != os.getuid():
        continue

    if S_ISDIR(fstat.st_mode):
        statfile = os.path.join(pathname, 'stat')
        if os.path.isfile(statfile):
            with open(statfile) as f:
                statline = f.readline()
                fields   = statline.split()
                if len(fields) >= 3:
                    process_pid  = fields[0]
                    process_ppid = fields[3]

                    if process_pid == str(myppid):
                       ProcessPid = process_ppid

                    if CountJobs.has_key(process_ppid):
                       CountJobs[process_ppid] += 1
                    else:
                       CountJobs[process_ppid]  = 1

num_jobs = CountJobs[str(ProcessPid)] - 1
if num_jobs > 0:
    powerline.append(' %d ' % num_jobs, Color.JOBS_FG, Color.JOBS_BG)
```

On my slow laptop this is significantly (5 to 10) times faster.

**Comment by b-ryan** [comment]
This is old - there was an attempt to implement this here: https://github.com/banga/powerline-shell/pull/119/files

I closed it primarily due to the code being more complicated. I didn't hear any backlash on that. I also just released a new version of powerline-shell which is capable of running segments in parallel. I didn't actually migrate the jobs segment to do its stuff in a thread, but that would be the lower-hanging fruit towards optimization.
