### ISSUE TITLE
Problem with pyenv

### ISSUE THREAD

**Issue by LeonardoGentile** [banga/powerline-shell#247]
Hello,
I haven't updated my powerline-shell for a while since everything was working fine.
So far I've always used python 2.6 or 2.7, but now after installing pyenv and setting the global python to be 3.5.0 things started to break.

So I've updated to the latest commit of powerline-shell and reinstalled it using python 3. Everything back to normal, apart some different icons that I will try to change somehow.

The problem starts when using a virtualenv or a specific folder where I set another version of python (using pyenv) different from python 3, that could be python 2.7 or or python 2.6.

When the active version of python is < 3 then the prompt just disappear.

Is there any fix for this?

**Comment by LeonardoGentile** [comment]
The problem comes from line 9: `py3 = sys.version_info.major == 3`, in fact `sys.version_info` produce different output depending on the python version:
```
# 2.6.6
(2, 6, 6, 'final', 0)

# 3.5.0
sys.version_info(major=3, minor=5, micro=0, releaselevel='final', serial=0)
```
So when using python 2.6.6 from pyenv there is no `major` attributes.
Can't we just take the first positional attribute?

**Comment by InnovativeInventor** [comment]
@LeonardoGentile I had the same problem. I added my solution to the wiki (I use fish, but the solution should be similar for other shells). The problem is that your shell can't find `powerline-shell` if it isn't installed in the virtualenv or pyenv that you're in.

https://github.com/b-ryan/powerline-shell/wiki/Using-with-Fish
