### ISSUE TITLE
lock and network have the same symbol

### ISSUE THREAD

**Issue by nschloe** [banga/powerline-shell#287]
Probably a typo in `./powerline-shell.py`:
```
            'lock': u'\uE0A2',
            'network': u'\uE0A2',
```
Also, the place [`U+1F512`](http://www.fileformat.info/info/unicode/char/1f512/index.htm) might by better suited for the lock.

As for SSH, I'm wondering what symbol is supposed to suggest that the connection is remote. A left-right arrow perhaps (e.g., [`U+2194`](http://www.fileformat.info/info/unicode/char/2194/index.htm))? I personally find the letters `SSH` more appropriate than any symbol here.

**Comment by b-ryan** [comment]
I noticed this recently. The reason it was implemented this way seems to be that the `powerline` project uses the lock symbol for SSH. I think there are also limitations to which characters can be used due to the fonts that are available.

I agree with you that `SSH` would more appropriate. I say we go ahead and change it.

**Comment by b-ryan** [comment]
Just released this change. Download the latest version with `pip install --upgrade --no-cache-dir powerline-shell`
