### ISSUE TITLE
Always display same prompt

### ISSUE THREAD

**Issue by jherran** [banga/powerline-shell#324]
I don't know why, but with default configuration I always get the same prompt:
username | machine | ~ | $
No git, no path, etc.

If I sudo su, all works fine. I'm on a osx 10.13.1 with python 2.7.14. I recently install powerline-shell through pip, before that, all works as expected.

Could someone point me on how can I solve this issue?

**Comment by b-ryan** [comment]
What shell are you using? Is it bash? Can you paste the relevant portion of your configuration file as described in the README? Ie. your bashrc, zshrc, or whatever file you updated?

**Comment by jherran** [comment]
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)

**Comment by jceaser** [comment]
I had quite a bit of trouble before two, especially since I had installed a lot of tools one day and there was a very similar named prompt tool out there. Can you break the prompt by putting bad data in the config file? That test will prove that your actually modifying the correct file and have the correct software loaded? Also, can you call the prompt by hand with `powerline-shell --help`?

**Comment by jherran** [comment]
With `powerline-shell --shell bare` seems that works good. `powerline-shell --help` shows the help as usual.

If I break my $HOME/.powerline-shell.json nothin happens. Why?

**Comment by jherran** [comment]
On file `__init__.py`, If I remove the `"powerline-shell.json"` line, or change the order, my configuration file was read, and if I break it, I get an error.

`def find_config():`
`    for location in [`
`        "powerline-shell.json",`
`        "~/.powerline-shell.json",`
`    ]:`
`        full = os.path.expanduser(location)`
`        if os.path.exists(full):`
`            return full`

**Comment by jherran** [comment]
Ok, I was able to solve it uninstalling [bash-preexec](https://github.com/rcaloras/bash-preexec).
